'use strict';
const $=id=>document.getElementById(id);
const state={rows:[],gt:[],headers:[],start:0,end:120,fs:1000,signal:'accel_vertical_mps2'};

function setStatus(s){$('appStatus').textContent=s}
function parseCSV(text){
  const lines=text.trim().split(/\r?\n/); if(!lines.length) return [];
  const headers=lines[0].split(',').map(x=>x.trim());
  const out=new Array(lines.length-1);
  for(let i=1;i<lines.length;i++){
    const v=lines[i].split(','); const r={};
    for(let j=0;j<headers.length;j++){ const raw=(v[j]??'').trim(); const n=Number(raw); r[headers[j]]=raw!==''&&Number.isFinite(n)?n:raw; }
    out[i-1]=r;
  }
  return {headers,rows:out};
}
async function readFile(file){return parseCSV(await file.text())}
async function loadDemo(){
  try{ setStatus('Loading demo…'); const [a,b]=await Promise.all([fetch('data/EV_vibration_1ms_2min_student.csv'),fetch('data/EV_vibration_1ms_2min_ground_truth.csv')]);
    if(!a.ok) throw new Error('Demo CSV fetch failed');
    const data=parseCSV(await a.text()); const gt=b.ok?parseCSV(await b.text()):{rows:[]}; setDataset(data); state.gt=gt.rows; analyze(); setStatus('Demo loaded');
  }catch(e){setStatus('Upload CSV manually'); alert('If you opened index.html directly, the browser may block bundled CSV loading. Upload the CSV manually, or open the app through GitHub Pages / a local web server.');}
}
function setDataset(data){ state.headers=data.headers; state.rows=data.rows; const dt=median(data.rows.slice(0,5000).map(r=>+r.dt_s).filter(Number.isFinite)); state.fs=dt?1/dt:1000; state.start=+data.rows[0]?.timestamp_s||0; state.end=+data.rows[data.rows.length-1]?.timestamp_s||state.start; $('startTime').value=state.start.toFixed(3); $('endTime').value=state.end.toFixed(3); $('fileInfo').textContent=`${data.rows.length.toLocaleString()} rows · ${data.headers.length} columns`; }
function median(a){if(!a.length)return NaN;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2}
function vals(rows,key){return rows.map(r=>+r[key]).filter(Number.isFinite)}
function stats(a){if(!a.length)return {n:0,min:0,max:0,mean:0,rms:0,std:0,peak:0,ptp:0,crest:0};let min=Infinity,max=-Infinity,sum=0,s2=0;for(const x of a){if(x<min)min=x;if(x>max)max=x;sum+=x;s2+=x*x}const mean=sum/a.length,rms=Math.sqrt(s2/a.length);let vs=0;for(const x of a)vs+=(x-mean)**2;const std=Math.sqrt(vs/a.length),peak=Math.max(Math.abs(min),Math.abs(max));return {n:a.length,min,max,mean,rms,std,peak,ptp:max-min,crest:rms?peak/rms:0}}
function windowRows(){return state.rows.filter(r=>+r.timestamp_s>=state.start&&+r.timestamp_s<=state.end)}
function f(x,d=3){return Number.isFinite(x)?x.toFixed(d):'—'}
function cards(items){$('overviewCards').innerHTML=items.map(([l,v])=>`<div class="card"><div class="label">${l}</div><div class="value">${v}</div></div>`).join('')}
function analyze(){ if(!state.rows.length)return; state.signal=$('signalSelect').value; const wr=windowRows(), x=vals(wr,state.signal), st=stats(x), duration=state.rows.length?+state.rows.at(-1).timestamp_s-(+state.rows[0].timestamp_s):0;
 cards([['Samples',state.rows.length.toLocaleString()],['Duration',f(duration,3)+' s'],['Sampling Fs',f(state.fs,1)+' Hz'],['dt',f(1/state.fs,6)+' s'],['Selected RMS',f(st.rms,5)],['STD',f(st.std,5)],['Peak',f(st.peak,5)],['Peak-to-Peak',f(st.ptp,5)],['Mean',f(st.mean,6)],['Nyquist',f(state.fs/2,1)+' Hz'],['Window',f(state.end-state.start,2)+' s'],['Signal',state.signal.includes('vertical')?'Vertical':'Lateral']]);
 $('rangeLabel').textContent=`${f(state.start,2)}–${f(state.end,2)} s`; drawAll(wr,x,st); }

function resizeCanvas(c){const dpr=window.devicePixelRatio||1,w=c.clientWidth,h=+c.getAttribute('height');c.width=Math.max(300,Math.floor(w*dpr));c.height=Math.floor(h*dpr);const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return {ctx,w,h}}
function linePlot(canvas, series, opts={}){ const {ctx,w,h}=resizeCanvas(canvas);ctx.clearRect(0,0,w,h);const pad={l:52,r:18,t:16,b:32};const allX=series.flatMap(s=>s.x),allY=series.flatMap(s=>s.y);if(!allX.length)return;let xmin=Math.min(...allX),xmax=Math.max(...allX),ymin=Math.min(...allY),ymax=Math.max(...allY);if(ymin===ymax){ymin-=1;ymax+=1}const xp=x=>pad.l+(x-xmin)/(xmax-xmin||1)*(w-pad.l-pad.r),yp=y=>h-pad.b-(y-ymin)/(ymax-ymin||1)*(h-pad.t-pad.b);ctx.strokeStyle='#26405c';ctx.lineWidth=1;for(let i=0;i<=5;i++){let yy=pad.t+i*(h-pad.t-pad.b)/5;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke()}ctx.fillStyle='#8ea6bf';ctx.font='11px Segoe UI';ctx.fillText(opts.xLabel||'',w/2-20,h-8);ctx.save();ctx.translate(12,h/2);ctx.rotate(-Math.PI/2);ctx.fillText(opts.yLabel||'',0,0);ctx.restore();const colors=['#35b7ff','#ffb74d','#46d6a4','#ff6b6b','#b39ddb'];series.forEach((s,si)=>{ctx.strokeStyle=colors[si%colors.length];ctx.lineWidth=1.4;ctx.beginPath();for(let i=0;i<s.x.length;i++){const px=xp(s.x[i]),py=yp(s.y[i]);if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py)}ctx.stroke()});ctx.fillStyle='#8ea6bf';ctx.fillText(f(xmin,1),pad.l,h-14);ctx.fillText(f(xmax,1),w-pad.r-35,h-14);ctx.fillText(f(ymax,3),4,pad.t+5);ctx.fillText(f(ymin,3),4,h-pad.b);}
function decimateXY(rows,ykey,max=2500){const step=Math.max(1,Math.floor(rows.length/max)),x=[],y=[];for(let i=0;i<rows.length;i+=step){x.push(+rows[i].timestamp_s);y.push(+rows[i][ykey])}return {x,y}}
function drawAll(wr,x,st){ const speed=decimateXY(wr,'vehicle_speed_kmh'),wheel=decimateXY(wr,'wheel_rotation_hz'),motor=decimateXY(wr,'estimated_motor_order_hz');linePlot($('timelineCanvas'),[speed,wheel,motor],{xLabel:'Time (s)',yLabel:'Operating values'});linePlot($('rawCanvas'),[decimateXY(wr,state.signal)],{xLabel:'Time (s)',yLabel:'Acceleration (m/s²)'});
 const filtered=applyFilter(x,state.fs,$('filterType').value,+$('lowCut').value,+$('highCut').value);linePlot($('filterCanvas'),[sampleSeries(wr,x),sampleSeries(wr,filtered)],{xLabel:'Time (s)',yLabel:'m/s²'});$('filterMetrics').innerHTML=metricCompare('Raw',stats(x),'Filtered',stats(filtered));
 const kal=kalman(x,10**(+$('logQ').value),10**(+$('logR').value));linePlot($('kalmanCanvas'),[sampleSeries(wr,x),sampleSeries(wr,kal.estimate),sampleSeries(wr,kal.innovation)],{xLabel:'Time (s)',yLabel:'Signal / innovation'});const ist=stats(kal.innovation);$('kalmanMetrics').innerHTML=table([['Q',(10**(+$('logQ').value)).toExponential(2)],['R',(10**(+$('logR').value)).toExponential(2)],['Innovation RMS',f(ist.rms,6)],['Innovation STD',f(ist.std,6)],['Max |innovation|',f(ist.peak,6)]]);
 const spec=fftSpectrum(x,state.fs), peaks=findPeaks(spec.freq,spec.amp,6);linePlot($('fftCanvas'),[{x:spec.freq,y:spec.amp}],{xLabel:'Frequency (Hz)',yLabel:'Amplitude'});$('peakTable').innerHTML=table([['Peak #','Frequency','Amplitude'],...peaks.map((p,i)=>[i+1,f(p.f,2)+' Hz',f(p.a,5)])],true);
 const ens=ensemble(x,state.fs,+$('segmentSec').value);linePlot($('ensembleCanvas'),ens.avg.length?[{x:ens.t,y:ens.avg}]:[],{xLabel:'Segment time (s)',yLabel:'Average'});$('ensembleMetrics').innerHTML=table([['Segments',ens.n],['Segment samples',ens.len],['RMS before',f(st.rms,6)],['RMS ensemble',f(stats(ens.avg).rms,6)],['Residual RMS',f(ens.residualRms,6)]]);
 diagnosis(wr,x,st,spec,kal); groundTruth(); summary(st,peaks); }
function sampleSeries(wr,a,max=2500){const step=Math.max(1,Math.floor(a.length/max)),xx=[],yy=[];for(let i=0;i<a.length;i+=step){xx.push(+wr[i]?.timestamp_s||i/state.fs);yy.push(a[i])}return{x:xx,y:yy}}
function metricCompare(n1,a,n2,b){return table([['Metric',n1,n2],['RMS',f(a.rms,6),f(b.rms,6)],['Peak',f(a.peak,6),f(b.peak,6)],['STD',f(a.std,6),f(b.std,6)],['Peak-to-Peak',f(a.ptp,6),f(b.ptp,6)],['Crest Factor',f(a.crest,3),f(b.crest,3)]],true)}
function table(rows,header=false){return `<table>${rows.map((r,i)=>`<tr>${r.map(c=>(header&&i===0)?`<th>${c}</th>`:`<td>${c}</td>`).join('')}</tr>`).join('')}</table>`}

function onePoleLowpass(x,fs,fc){fc=Math.min(fc,fs*.49);const a=1-Math.exp(-2*Math.PI*fc/fs),y=new Array(x.length);let prev=x[0]||0;for(let i=0;i<x.length;i++){prev+=a*(x[i]-prev);y[i]=prev}return y}
function onePoleHighpass(x,fs,fc){const lp=onePoleLowpass(x,fs,fc);return x.map((v,i)=>v-lp[i])}
function zeroPhase(fn,x){const y=fn(x),z=fn([...y].reverse());return z.reverse()}
function applyFilter(x,fs,type,lo,hi){if(type==='none')return [...x];lo=Math.max(.1,Math.min(lo,fs*.49));hi=Math.max(.1,Math.min(hi,fs*.49));if(lo>hi)[lo,hi]=[hi,lo];if(type==='lowpass')return zeroPhase(a=>onePoleLowpass(a,fs,hi),x);if(type==='highpass')return zeroPhase(a=>onePoleHighpass(a,fs,lo),x);if(type==='bandpass')return zeroPhase(a=>onePoleLowpass(onePoleHighpass(a,fs,lo),fs,hi),x);if(type==='bandstop'){const bp=zeroPhase(a=>onePoleLowpass(onePoleHighpass(a,fs,lo),fs,hi),x);return x.map((v,i)=>v-bp[i])}return [...x]}
function kalman(z,Q,R){const estimate=new Array(z.length),innovation=new Array(z.length);let x=z[0]||0,P=1;for(let k=0;k<z.length;k++){const xp=x,Pp=P+Q,y=z[k]-xp,S=Pp+R,K=Pp/S;x=xp+K*y;P=(1-K)*Pp;estimate[k]=x;innovation[k]=y}return{estimate,innovation}}
function ensemble(x,fs,segSec){const len=Math.max(8,Math.floor(segSec*fs)),n=Math.floor(x.length/len);if(n<1)return{avg:[],t:[],n:0,len,residualRms:0};const avg=new Array(len).fill(0);for(let s=0;s<n;s++)for(let i=0;i<len;i++)avg[i]+=x[s*len+i]/n;let rs=0,c=0;for(let s=0;s<n;s++)for(let i=0;i<len;i++){const d=x[s*len+i]-avg[i];rs+=d*d;c++}return{avg,t:avg.map((_,i)=>i/fs),n,len,residualRms:Math.sqrt(rs/(c||1))}}
function nextPow2(n){let p=1;while(p<n)p<<=1;return p}
function fftSpectrum(input,fs){if(input.length<8)return{freq:[],amp:[]};let n=1;while((n<<1)<=Math.min(input.length,16384))n<<=1;const re=new Float64Array(n),im=new Float64Array(n),offset=Math.max(0,Math.floor((input.length-n)/2));for(let i=0;i<n;i++){const w=.5-.5*Math.cos(2*Math.PI*i/(n-1));re[i]=(input[offset+i]||0)*w}for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[re[i],re[j]]=[re[j],re[i]];[im[i],im[j]]=[im[j],im[i]]}}for(let len=2;len<=n;len<<=1){const ang=-2*Math.PI/len;for(let i=0;i<n;i+=len){for(let j=0;j<len/2;j++){const c=Math.cos(ang*j),s=Math.sin(ang*j),ur=re[i+j],ui=im[i+j],vr=re[i+j+len/2]*c-im[i+j+len/2]*s,vi=re[i+j+len/2]*s+im[i+j+len/2]*c;re[i+j]=ur+vr;im[i+j]=ui+vi;re[i+j+len/2]=ur-vr;im[i+j+len/2]=ui-vi}}}const m=Math.floor(n/2),freq=[],amp=[];for(let i=0;i<m;i++){freq.push(i*fs/n);amp.push(2*Math.hypot(re[i],im[i])/n)}return{freq,amp}}
function findPeaks(freq,amp,n){const arr=[];for(let i=2;i<amp.length-2;i++)if(amp[i]>amp[i-1]&&amp[i]>=amp[i+1])arr.push({f:freq[i],a:amp[i]});return arr.sort((a,b)=>b.a-a.a).slice(0,n)}
function bandEnergy(spec,center,tol){let s=0;for(let i=0;i<spec.freq.length;i++)if(Math.abs(spec.freq[i]-center)<=tol)s+=spec.amp[i]*spec.amp[i];return s}
function diagnosis(wr,x,st,spec,kal){const tol=+$('orderTol').value||2;const motorVals=vals(wr,'estimated_motor_order_hz'),wheelVals=vals(wr,'wheel_rotation_hz');const mf=median(motorVals),wf=median(wheelVals);const me=[1,2,3].reduce((s,h)=>s+bandEnergy(spec,mf*h,tol),0),we=[1,2].reduce((s,h)=>s+bandEnergy(spec,wf*h,tol),0);let low=0,total=0;for(let i=0;i<spec.freq.length;i++){const e=spec.amp[i]**2;total+=e;if(spec.freq[i]<=15)low+=e}const lowRatio=total?low/total:0;const ist=stats(kal.innovation),thr=Math.abs(ist.mean)+(+$('innovN').value||3)*ist.std;let spikes=0;for(const y of kal.innovation)if(Math.abs(y)>thr)spikes++;const spikeRate=kal.innovation.length?spikes/kal.innovation.length:0;
 const base=.024;const rmsRise=Math.max(0,(st.rms-base)/.07);const motorNorm=me/(me+we+1e-12),roadNorm=we/(me+we+1e-12);let motorScore=100*Math.min(1,.48*motorNorm+.32*Math.min(1,rmsRise)+.20*(1-lowRatio));let roadScore=100*Math.min(1,.38*roadNorm+.34*Math.min(1,lowRatio*2)+.28*Math.min(1,spikeRate/.01));if(!Number.isFinite(motorScore))motorScore=0;if(!Number.isFinite(roadScore))roadScore=0;
 const m=Math.round(motorScore),r=Math.round(roadScore);$('motorScore').textContent=m;$('roadScore').textContent=r;$('motorBar').style.width=m+'%';$('roadBar').style.width=r+'%';let cls='Normal / Low Evidence',text='Evidence is low for both sources in the selected window.';if(m>=45&&r>=45){cls='Mixed / Ambiguous';text='Evidence suggests both motor-related and road-related contributions. Further engineering analysis is recommended.'}else if(m>=45){cls='Likely Motor-related';text='Evidence suggests persistent/order-related vibration near the motor reference frequency and harmonics.'}else if(r>=45){cls='Likely Road-related';text='Evidence suggests transient, low-frequency, wheel-related or impact-type vibration.'}$('classification').textContent=cls;$('diagnosisText').textContent=text;$('diagnosisDetails').innerHTML=table([['Feature','Value'],['Representative motor order',f(mf,2)+' Hz'],['Representative wheel frequency',f(wf,2)+' Hz'],['Motor order energy',me.toExponential(3)],['Wheel order energy',we.toExponential(3)],['Low-frequency energy ratio',f(lowRatio*100,1)+'%'],['Innovation spike rate',f(spikeRate*100,2)+'%'],['Selected RMS',f(st.rms,6)]],true);}
function groundTruth(){const p=$('gtPanel');if(!state.gt.length){p.className='empty-state';p.textContent='No Ground Truth loaded.';return}if(!$('revealGT').checked){p.className='empty-state';p.textContent='Ground Truth is available but hidden. Turn on “Reveal Ground Truth” after completing your analysis.';return}const g=state.gt.filter(r=>+r.timestamp_s>=state.start&&+r.timestamp_s<=state.end);const road=g.length?g.reduce((s,r)=>s+(+r.ground_truth_road_event||0),0)/g.length:0;const motor=g.length?g.reduce((s,r)=>s+(+r.ground_truth_motor_abnormal||0),0)/g.length:0;let cls='Normal';if(road>.2&&motor>.2)cls='Road + Motor';else if(road>.2)cls='Road Event';else if(motor>.2)cls='Motor Abnormal';p.className='metrics-table';p.innerHTML=table([['Ground Truth','Value'],['Window classification',cls],['Road-event proportion',f(road*100,1)+'%'],['Motor-abnormal proportion',f(motor*100,1)+'%'],['Samples',g.length.toLocaleString()]],true)}
function summary(st,peaks){const p=peaks[0];$('summary').innerHTML=`Selected window <strong>${f(state.start,2)}–${f(state.end,2)} s</strong> contains ${windowRows().length.toLocaleString()} samples. RMS = <strong>${f(st.rms,6)} m/s²</strong>, Peak = <strong>${f(st.peak,6)} m/s²</strong>${p?`, and the strongest detected FFT peak is near <strong>${f(p.f,2)} Hz</strong>.`:'.'} Use amplitude together with spectral/order evidence and transient behavior; RMS alone cannot determine whether vibration originates from the road or motor/drivetrain.`}

$('loadDemoBtn').onclick=loadDemo;
$('csvInput').onchange=async e=>{if(e.target.files[0]){setStatus('Parsing CSV…');setDataset(await readFile(e.target.files[0]));analyze();setStatus('Dataset loaded')}};
$('gtInput').onchange=async e=>{if(e.target.files[0]){state.gt=(await readFile(e.target.files[0])).rows;groundTruth();setStatus('Ground Truth loaded')}};
$('applyRangeBtn').onclick=()=>{state.start=+$('startTime').value;state.end=+$('endTime').value;if(state.end<state.start)[state.start,state.end]=[state.end,state.start];analyze()};
$('fullRangeBtn').onclick=()=>{state.start=+state.rows[0]?.timestamp_s||0;state.end=+state.rows.at(-1)?.timestamp_s||120;$('startTime').value=state.start;$('endTime').value=state.end;analyze()};
['signalSelect','filterType','lowCut','highCut','segmentSec','orderTol','innovN'].forEach(id=>$(id).onchange=analyze);
['logQ','logR'].forEach(id=>$(id).oninput=()=>{$('qLabel').textContent='Q='+(10**(+$('logQ').value)).toExponential(1);$('rLabel').textContent='R='+(10**(+$('logR').value)).toExponential(1);if(state.rows.length)analyze()});
$('revealGT').onchange=groundTruth;window.addEventListener('resize',()=>state.rows.length&&analyze());$('qLabel').textContent='Q=1.0e-5';$('rLabel').textContent='R=1.0e-3';
